#!/bin/bash
# Hash's shader content with sha256 and serves back contents of file with matching filename.

tmp="$(mktemp)"
trap 'rm "$tmp"' EXIT
cat > "$tmp"

hash="$(sha256sum < "$tmp" | awk '{print $1}')"
path="${SHADER_PATH:-./shaders}/$hash"

if [[ -f "$path" ]]; then
   printf "reading shader: %s\n" "$path" 1>&2
   cat "$path"
else
   printf "hash mismatch: %s\n" "$hash" 1>&2
   cat "$tmp"
fi
